version: '3'

includes:
  shared: ../Taskfile.yaml

vars:
  AWS_CREDENTIALS_PATH: "/home/jhabibi/development/spaces-demo/startup/startup-auto/aws-credentials-file.txt"
  UPBOUND_ORG: "upbound-demo"
  UPBOUND_ORG_TEAM: "CI"
  SPACE: "spaces-idp"
  ROOT_GROUP_NAME: "solution-idp-non-prod"
  ROOT_CTP_NAME: "bootstrap"
  GIT_REPO: "https://github.com/upbound-demo/solution-idp.git"
  GIT_REVISION: "main"

tasks:
  bootstrap:
    desc: Bootstrap non-prod environment
    cmds:
      - task: shared:check-up-profile
      - task: shared:bootstrap-group
      - task: shared:bootstrap-ctp
      - task: shared:bootstrap-configurations
      - task: shared:bootstrap-provider-kubernetes-with-pat
      - task: shared:bootstrap-argocd-application
      # self-hosted-space without proidc
      - task: shared:bootstrap-aws-credentials
      - task: shared:post-bootstrap