apiVersion: platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"custom","basePath":"state/solution-idp-non-prod/frontend/30-claims"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/javid
    terasky.backstage.io/system: default
    terasky.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/main/state/solution-idp-non-prod/frontend/30-claims/gartner-demo-database.yaml
  name: gartner-demo-database
  namespace: default
spec:
  parameters:
    cloud: Azure
    deletionPolicy: Delete
    engine: postgres
    engineVersion: '11'
    region: uswest
    storageGB: 32
  compositeDeletePolicy: Background
